### ISSUE TITLE
What is going on on Marketplace?

### ISSUE THREAD

**Issue by frederikhors** [jinliming2/vscode-go-template#16]
What is going on?

![image](https://user-images.githubusercontent.com/41120635/174662029-cc19924c-9b84-49f6-a985-720ed84ee551.png)

**Comment by frederikhors** [comment]
@jinliming2 please, can you help us?

**Comment by frederikhors** [comment]
@jinliming2 please, can you help us?

**Comment by jinliming2** [comment]
> @jinliming2 please, can you help us?

Fixed.

**Comment by frederikhors** [comment]
Thanks. It works. What happened?

**Comment by jinliming2** [comment]
> Thanks. It works. What happened?

Sorry, I haven't had much time to maintain all my open source repositories lately.
I will try to fix some issues with this plugin when I have some free time.

**Comment by frederikhors** [comment]
I was referring to the marketplace issue. Did Microsoft take it down? Why?

**Comment by jinliming2** [comment]
> I was referring to the marketplace issue. Did Microsoft take it down? Why?

I changed my account settings a few days ago and I think I may have performed some wrong action.
