### ISSUE TITLE
Support configurable file extension

### ISSUE THREAD

**Issue by nightofmind** [jinliming2/vscode-go-template#3]
Maybe configure like ```go-template-extra-file-extensions: 'gotmpl'``` makes files whose name matched `*.gotmpl` can also be identified as an go template file is really useful.

**Comment by jinliming2** [comment]
You can add your extension name to the `files.associations` in the settings to achieve this.
For example:
```json
{
    "files.associations": {
        "*.gotmpl": "go-template"
    }
}
```
![image](https://user-images.githubusercontent.com/10294977/103904029-afd5af00-5137-11eb-94e2-5b36488cf9db.png)

**Comment by dannyharding10** [comment]
Will this work with file types that vscode already recognizes, like `.yaml` for example?

**Comment by jinliming2** [comment]
> Will this work with file types that vscode already recognizes, like `.yaml` for example?

No, this breaks syntax highlight for internal languages.
I'm implementing a new version try to solve this, but only for keywords highlighting. It's a little bit hard to implement an embedded language due to [an unresolved issue](https://github.com/microsoft/vscode/issues/1751) of VSCode.

**Comment by jinliming2** [comment]
I just published a new version (v0.1.0), including custom file extension config support, pls have a try and give feedback, thanks.

![image](https://user-images.githubusercontent.com/10294977/104922474-c00e4980-59d5-11eb-8e22-0dfc83fa37ec.png)

**Comment by nightofmind** [comment]
> I just published a new version (v0.1.0), including custom file extension config support, pls have a try and give feedback, thanks.
> 
> ![image](https://user-images.githubusercontent.com/10294977/104922474-c00e4980-59d5-11eb-8e22-0dfc83fa37ec.png)

yes, it works!

**Comment by sekaninat** [comment]
Hello, this seems promising :crossed_fingers: , but my editor doesn't recognize that it is i.e. yaml file when its name ends with `.yaml.tmpl`. So only the template syntax is highlighted but not yaml syntax.

Is there any solution to this please?

**Comment by balusarakesh** [comment]
I'm having the same problem as above
