### ISSUE TITLE
Highlight inside markdown fenced code block

### ISSUE THREAD

**Issue by outofsyncme** [jinliming2/vscode-go-template#4]
Would like to see highlighted go template inside fenced code block in a markdown file.

For example, in a `test.md` file:

~~~~
```go-html-template
  <title>
    {{- if .IsHome }}
      {{- $.Site.Title }}
    {{ else }}
       Not home toto
    {{ end -}}
  </title>
```
~~~~

**Comment by jinliming2** [comment]
Hi, I just published v0.0.2 to support Markdown, have a try.
